# Generated by Django 5.0.3 on 2024-03-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.IntegerField(default=40)),
                ('available_seats', models.IntegerField(default=40)),
            ],
        ),
    ]
